### PR TITLE
Added sensor name to example file

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by brentru** [comment]
@dherrada  Please include `_simpletest` before the `.py` extension on this example file.

**Comment by evaherrada** [comment]
Done

**Comment by brentru** [comment]
@dherrada Please change the docs to include the new filename on line:

`.. literalinclude:: ../examples/ds2413_simpletest.py`

https://github.com/adafruit/Adafruit_CircuitPython_DS2413/blob/master/docs/examples.rst

**Review by sommersoft — APPROVED** [review]
Excellent! Thanks @dherrada!

**Pull request merged**
